repos:
  - repo: https://github.com/astral-sh/ruff-pre-commit
    rev: v0.6.9
    hooks:
      - id: ruff
        args: [--fix]
      - id: ruff-format
  - repo: https://github.com/pre-commit/mirrors-mypy
    rev: v1.11.2
    hooks:
      - id: mypy
        additional_dependencies:
          [types-tabulate, types-requests, click, rich, pypinyin, pytest]
        args: [--strict, hsg]
        pass_filenames: false
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.6.0
    hooks:
      - id: end-of-file-fixer
        exclude: ^(assets/|\.vscode/|\.opencode/)
      - id: trailing-whitespace
        exclude: ^assets/
      - id: mixed-line-ending
        args: [--fix=lf]
        exclude: ^assets/
